/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2022-04-27 01:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"pull-right hidden-xs\">\r\n");
      out.write("          <b>Version</b> 2.0\r\n");
      out.write("        </div>\r\n");
      out.write("        <strong>Copyright &copy; 2014-2015 <a href=\"http://almsaeedstudio.com\">Almsaeed Studio</a>.</strong> All rights reserved.\r\n");
      out.write("      </footer>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Control Sidebar -->      \r\n");
      out.write("      <aside class=\"control-sidebar control-sidebar-dark\">                \r\n");
      out.write("        <!-- Create the tabs -->\r\n");
      out.write("        <ul class=\"nav nav-tabs nav-justified control-sidebar-tabs\">\r\n");
      out.write("          <li><a href=\"#control-sidebar-home-tab\" data-toggle=\"tab\"><i class=\"fa fa-home\"></i></a></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><a href=\"#control-sidebar-settings-tab\" data-toggle=\"tab\"><i class=\"fa fa-gears\"></i></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- Tab panes -->\r\n");
      out.write("        <div class=\"tab-content\">\r\n");
      out.write("          <!-- Home tab content -->\r\n");
      out.write("          <div class=\"tab-pane\" id=\"control-sidebar-home-tab\">\r\n");
      out.write("            <h3 class=\"control-sidebar-heading\">Recent Activity</h3>\r\n");
      out.write("            <ul class='control-sidebar-menu'>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>\r\n");
      out.write("                  <i class=\"menu-icon fa fa-birthday-cake bg-red\"></i>\r\n");
      out.write("                  <div class=\"menu-info\">\r\n");
      out.write("                    <h4 class=\"control-sidebar-subheading\">Langdon's Birthday</h4>\r\n");
      out.write("                    <p>Will be 23 on April 24th</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>\r\n");
      out.write("                  <i class=\"menu-icon fa fa-user bg-yellow\"></i>\r\n");
      out.write("                  <div class=\"menu-info\">\r\n");
      out.write("                    <h4 class=\"control-sidebar-subheading\">Frodo Updated His Profile</h4>\r\n");
      out.write("                    <p>New phone +1(800)555-1234</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>\r\n");
      out.write("                  <i class=\"menu-icon fa fa-envelope-o bg-light-blue\"></i>\r\n");
      out.write("                  <div class=\"menu-info\">\r\n");
      out.write("                    <h4 class=\"control-sidebar-subheading\">Nora Joined Mailing List</h4>\r\n");
      out.write("                    <p>nora@example.com</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>\r\n");
      out.write("                  <i class=\"menu-icon fa fa-file-code-o bg-green\"></i>\r\n");
      out.write("                  <div class=\"menu-info\">\r\n");
      out.write("                    <h4 class=\"control-sidebar-subheading\">Cron Job 254 Executed</h4>\r\n");
      out.write("                    <p>Execution time 5 seconds</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul><!-- /.control-sidebar-menu -->\r\n");
      out.write("\r\n");
      out.write("            <h3 class=\"control-sidebar-heading\">Tasks Progress</h3> \r\n");
      out.write("            <ul class='control-sidebar-menu'>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>               \r\n");
      out.write("                  <h4 class=\"control-sidebar-subheading\">\r\n");
      out.write("                    Custom Template Design\r\n");
      out.write("                    <span class=\"label label-danger pull-right\">70%</span>\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <div class=\"progress progress-xxs\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-danger\" style=\"width: 70%\"></div>\r\n");
      out.write("                  </div>                                    \r\n");
      out.write("                </a>\r\n");
      out.write("              </li> \r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>               \r\n");
      out.write("                  <h4 class=\"control-sidebar-subheading\">\r\n");
      out.write("                    Update Resume\r\n");
      out.write("                    <span class=\"label label-success pull-right\">95%</span>\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <div class=\"progress progress-xxs\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-success\" style=\"width: 95%\"></div>\r\n");
      out.write("                  </div>                                    \r\n");
      out.write("                </a>\r\n");
      out.write("              </li> \r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>               \r\n");
      out.write("                  <h4 class=\"control-sidebar-subheading\">\r\n");
      out.write("                    Laravel Integration\r\n");
      out.write("                    <span class=\"label label-waring pull-right\">50%</span>\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <div class=\"progress progress-xxs\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-warning\" style=\"width: 50%\"></div>\r\n");
      out.write("                  </div>                                    \r\n");
      out.write("                </a>\r\n");
      out.write("              </li> \r\n");
      out.write("              <li>\r\n");
      out.write("                <a href='javascript::;'>               \r\n");
      out.write("                  <h4 class=\"control-sidebar-subheading\">\r\n");
      out.write("                    Back End Framework\r\n");
      out.write("                    <span class=\"label label-primary pull-right\">68%</span>\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <div class=\"progress progress-xxs\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-primary\" style=\"width: 68%\"></div>\r\n");
      out.write("                  </div>                                    \r\n");
      out.write("                </a>\r\n");
      out.write("              </li>               \r\n");
      out.write("            </ul><!-- /.control-sidebar-menu -->         \r\n");
      out.write("\r\n");
      out.write("          </div><!-- /.tab-pane -->\r\n");
      out.write("          <!-- Stats tab content -->\r\n");
      out.write("          <div class=\"tab-pane\" id=\"control-sidebar-stats-tab\">Stats Tab Content</div><!-- /.tab-pane -->\r\n");
      out.write("          <!-- Settings tab content -->\r\n");
      out.write("          <div class=\"tab-pane\" id=\"control-sidebar-settings-tab\">            \r\n");
      out.write("            <form method=\"post\">\r\n");
      out.write("              <h3 class=\"control-sidebar-heading\">General Settings</h3>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Report panel usage\r\n");
      out.write("                  <input type=\"checkbox\" class=\"pull-right\" checked />\r\n");
      out.write("                </label>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Some information about this general settings option\r\n");
      out.write("                </p>\r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Allow mail redirect\r\n");
      out.write("                  <input type=\"checkbox\" class=\"pull-right\" checked />\r\n");
      out.write("                </label>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Other sets of options are available\r\n");
      out.write("                </p>\r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Expose author name in posts\r\n");
      out.write("                  <input type=\"checkbox\" class=\"pull-right\" checked />\r\n");
      out.write("                </label>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Allow the user to show his name in blog posts\r\n");
      out.write("                </p>\r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("              <h3 class=\"control-sidebar-heading\">Chat Settings</h3>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Show me as online\r\n");
      out.write("                  <input type=\"checkbox\" class=\"pull-right\" checked />\r\n");
      out.write("                </label>                \r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Turn off notifications\r\n");
      out.write("                  <input type=\"checkbox\" class=\"pull-right\" />\r\n");
      out.write("                </label>                \r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"control-sidebar-subheading\">\r\n");
      out.write("                  Delete chat history\r\n");
      out.write("                  <a href=\"javascript::;\" class=\"text-red pull-right\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("                </label>                \r\n");
      out.write("              </div><!-- /.form-group -->\r\n");
      out.write("            </form>\r\n");
      out.write("          </div><!-- /.tab-pane -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </aside><!-- /.control-sidebar -->\r\n");
      out.write("      <!-- Add the sidebar's background. This div must be placed\r\n");
      out.write("           immediately after the control sidebar -->\r\n");
      out.write("      <div class='control-sidebar-bg'></div>\r\n");
      out.write("    </div><!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap 3.3.2 JS -->\r\n");
      out.write("    <script src=\"/resources/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- FastClick -->\r\n");
      out.write("    <script src='/resources/plugins/fastclick/fastclick.min.js'></script>\r\n");
      out.write("    <!-- AdminLTE App -->\r\n");
      out.write("    <script src=\"/resources/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- AdminLTE for demo purposes -->\r\n");
      out.write("    <script src=\"/resources/dist/js/demo.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
